kw-bookmedicine/backend

- .gitignore
- build.gradle
- src/main/java/kr/KWGraduate/BookPharmacy/dto/BookDto.java
- src/main/java/kr/KWGraduate/BookPharmacy/dto/BookSearchDto.java
- src/main/java/kr/KWGraduate/BookPharmacy/entity/Book.java
- src/main/java/kr/KWGraduate/BookPharmacy/entity/Categories.java
- src/main/java/kr/KWGraduate/BookPharmacy/entity/Client.java
- src/main/java/kr/KWGraduate/BookPharmacy/entity/ClientBook.java
- src/main/java/kr/KWGraduate/BookPharmacy/entity/ClientKeyword.java
- src/main/java/kr/KWGraduate/BookPharmacy/entity/Feed.java
- src/main/java/kr/KWGraduate/BookPharmacy/entity/KeywordItem.java
- src/main/java/kr/KWGraduate/BookPharmacy/repository/BookRepository.java
- src/main/java/kr/KWGraduate/BookPharmacy/repository/CategoryRepository.java
- src/main/java/kr/KWGraduate/BookPharmacy/service/BookService.java
- src/main/resources/application.yml
- src/test/java/kr/KWGraduate/BookPharmacy/repository/BookRepositoryTest.java
BookRepository 계층, Dto계층 개발 코드에 대하여 병합
> Merge repository-book

- build.gradle
- src/main/java/kr/KWGraduate/BookPharmacy/config/SwaggerConfiguration.java
- src/main/java/kr/KWGraduate/BookPharmacy/controller/SwaggerTestController.java
> Merge feature/swagger

- .gitignore
- build.gradle
- src/main/java/kr/KWGraduate/BookPharmacy/config/SwaggerConfiguration.java
- src/main/java/kr/KWGraduate/BookPharmacy/controller/SwaggerTestController.java
- src/main/java/kr/KWGraduate/BookPharmacy/dto/BookDto.java
- src/main/java/kr/KWGraduate/BookPharmacy/dto/BookSearchDto.java
- src/main/java/kr/KWGraduate/BookPharmacy/dto/ClientDto.java
- src/main/java/kr/KWGraduate/BookPharmacy/entity/Book.java
- src/main/java/kr/KWGraduate/BookPharmacy/entity/BookKeyword.java
- src/main/java/kr/KWGraduate/BookPharmacy/entity/Categories.java
- src/main/java/kr/KWGraduate/BookPharmacy/entity/Client.java
- src/main/java/kr/KWGraduate/BookPharmacy/entity/ClientBook.java
- src/main/java/kr/KWGraduate/BookPharmacy/entity/ClientKeyword.java
- src/main/java/kr/KWGraduate/BookPharmacy/entity/Feed.java
- src/main/java/kr/KWGraduate/BookPharmacy/entity/KeywordItem.java
- src/main/java/kr/KWGraduate/BookPharmacy/repository/BookRepository.java
- src/main/java/kr/KWGraduate/BookPharmacy/repository/CategoryRepository.java
- src/main/java/kr/KWGraduate/BookPharmacy/repository/ClientRepository.java
- src/main/java/kr/KWGraduate/BookPharmacy/service/BookService.java
- src/main/java/kr/KWGraduate/BookPharmacy/service/ClientService.java
- src/main/resources/application.yml
- src/test/java/kr/KWGraduate/BookPharmacy/entity/ClientTest.java
- src/test/java/kr/KWGraduate/BookPharmacy/repository/BookRepositoryTest.java
- src/test/java/kr/KWGraduate/BookPharmacy/repository/ClientRepositoryTest.java
- src/test/java/kr/KWGraduate/BookPharmacy/service/ClientServiceTest.java
merge: develop -> main (01/08)
> merge: develop -> main (01/08)

- src/main/java/kr/KWGraduate/BookPharmacy/dto/BookDto.java
- src/main/java/kr/KWGraduate/BookPharmacy/dto/BookSearchDto.java
- src/main/java/kr/KWGraduate/BookPharmacy/dto/FeedDto.java
- src/main/java/kr/KWGraduate/BookPharmacy/entity/Book.java
- src/main/java/kr/KWGraduate/BookPharmacy/entity/Feed.java
- src/main/java/kr/KWGraduate/BookPharmacy/repository/BookRepository.java
- src/main/java/kr/KWGraduate/BookPharmacy/repository/FeedRepository.java
- src/main/java/kr/KWGraduate/BookPharmacy/service/BookService.java
- src/main/java/kr/KWGraduate/BookPharmacy/service/FeedService.java
merge: repository-feed -> develop
> merge: repository-feed -> develop

- build.gradle
- src/main/java/kr/KWGraduate/BookPharmacy/controller/UserController.java
- src/main/java/kr/KWGraduate/BookPharmacy/dto/client/ClientJoinDto.java
- src/main/java/kr/KWGraduate/BookPharmacy/dto/client/ClientLoginDto.java
- src/main/java/kr/KWGraduate/BookPharmacy/exception/ErrorResult.java
- src/main/java/kr/KWGraduate/BookPharmacy/exception/controller/UserExceptionController.java
- src/main/java/kr/KWGraduate/BookPharmacy/exception/status/AllException.java
- src/main/java/kr/KWGraduate/BookPharmacy/exception/status/ExistEmailException.java
- src/main/java/kr/KWGraduate/BookPharmacy/exception/status/ExistIdException.java
- src/main/java/kr/KWGraduate/BookPharmacy/exception/status/ExistNicknameException.java
- src/main/java/kr/KWGraduate/BookPharmacy/exception/status/IsNotSamePasswordException.java
- src/main/java/kr/KWGraduate/BookPharmacy/exception/status/NoExistIdException.java
- src/main/java/kr/KWGraduate/BookPharmacy/service/ClientService.java
- src/test/java/kr/KWGraduate/BookPharmacy/service/ClientServiceTest.java
merge: controller-user -> develop
> merge: controller-user -> develop

- src/main/java/kr/KWGraduate/BookPharmacy/constant/BoardKeywordQuestion.java
- src/main/java/kr/KWGraduate/BookPharmacy/constant/QuestionDistractor.java
- src/main/java/kr/KWGraduate/BookPharmacy/dto/board/request/BoardCreateDto.java
- src/main/java/kr/KWGraduate/BookPharmacy/dto/board/request/BoardModifyDto.java
- src/main/java/kr/KWGraduate/BookPharmacy/dto/board/response/BoardMyPageDto.java
- src/main/java/kr/KWGraduate/BookPharmacy/dto/question/QuesAndDis.java
- src/main/java/kr/KWGraduate/BookPharmacy/entity/Answer.java
- src/main/java/kr/KWGraduate/BookPharmacy/entity/Board.java
- src/main/java/kr/KWGraduate/BookPharmacy/entity/Keyword.java
- src/main/java/kr/KWGraduate/BookPharmacy/entity/QuesAndDis.java
- src/main/java/kr/KWGraduate/BookPharmacy/enums/Keyword.java
- src/main/java/kr/KWGraduate/BookPharmacy/repository/AnswerRepository.java
- src/main/java/kr/KWGraduate/BookPharmacy/repository/BoardRepository.java
- src/main/java/kr/KWGraduate/BookPharmacy/service/BoardService.java
- src/test/java/kr/KWGraduate/BookPharmacy/repository/AnswerRepositoryTest.java
- src/test/java/kr/KWGraduate/BookPharmacy/repository/BoardRepositoryTest.java
- src/test/java/kr/KWGraduate/BookPharmacy/repository/PrescriptionRepositoryTest.java
- src/test/java/kr/KWGraduate/BookPharmacy/service/BoardServiceTest.java
- src/test/java/kr/KWGraduate/BookPharmacy/service/PrescriptionServiceTest.java
고민 키워드 추가, 선택지 추가 그리고 답변 엔티티 작성
closed #88
1. 키워드 내용 변경에 따른 enum클래스 이름 변경
2. constant패키지에서 질문들과 객관식 답변들을 작성
3. answer엔티티 작성 및 repository작성
4. 테스트 완료
> [Feat] 고민 키워드에 따른 질문, 선택지 필드 추가 및 답변 엔티티 작성

- src/main/java/kr/KWGraduate/BookPharmacy/entity/Board.java
- src/main/java/kr/KWGraduate/BookPharmacy/enums/Status.java
- src/main/java/kr/KWGraduate/BookPharmacy/repository/BoardRepository.java
- src/main/java/kr/KWGraduate/BookPharmacy/service/BoardService.java
- src/test/java/kr/KWGraduate/BookPharmacy/repository/BoardRepositoryTest.java
- src/test/java/kr/KWGraduate/BookPharmacy/service/BoardServiceTest.java
고민 게시판 상태 제거에 따른 코드 변경
closed #94
1. enums패키지에 있는 status클래스 제거
2. board repository에서 status에 따른 조회 쿼리 제거
3. board service에서 status에 따른 board찾는 메서드 제거
4. 그에 따른 테스트 코드 변경
> [Refactor] 고민 게시판 상태 제거에 따른 코드 변경

- src/main/java/kr/KWGraduate/BookPharmacy/entity/OneLinePrescription.java
- src/main/java/kr/KWGraduate/BookPharmacy/entity/ReadExperience.java
- src/main/java/kr/KWGraduate/BookPharmacy/repository/OneLinePrescriptionRepository.java
- src/main/java/kr/KWGraduate/BookPharmacy/repository/ReadExperienceRepository.java
- src/test/java/kr/KWGraduate/BookPharmacy/repository/OneLinePrescriptionRepositoryTest.java
- src/test/java/kr/KWGraduate/BookPharmacy/repository/ReadExperienceRepositoryTest.java
독서경험 및 한줄처방 엔티티 및 레포지토리 작성
- 독서경험 및 한줄처방 엔티티 및 레포지토리 작성
- 테스트코드 작성
> [Feat] 독서경험 및 한줄처방 엔티티 및 레포지토리 작성

- src/main/java/kr/KWGraduate/BookPharmacy/controller/BoardController.java
- src/main/java/kr/KWGraduate/BookPharmacy/controller/PrescriptionController.java
- src/main/java/kr/KWGraduate/BookPharmacy/dto/answer/request/AnswerCreateDto.java
- src/main/java/kr/KWGraduate/BookPharmacy/dto/board/request/BoardCreateDto.java
- src/main/java/kr/KWGraduate/BookPharmacy/dto/board/request/BoardModifyDto.java
- src/main/java/kr/KWGraduate/BookPharmacy/dto/board/response/BoardDetailDto.java
- src/main/java/kr/KWGraduate/BookPharmacy/service/BoardService.java
[Feat] 고민게시글 및 처방전 api작성
closed #105 
answer가 board에 종속적인 형태로 받도록 dto수정
answerService가 boardService에 종속적이도록 수정
처방전 및 게시판 api작성
> [Feat] 고민게시글 및 처방전 api작성

- src/main/java/kr/KWGraduate/BookPharmacy/entity/redis/RefreshToken.java
> [Refactor] redis유효시간 변경

- src/main/java/kr/KWGraduate/BookPharmacy/controller/SearchController.java
- src/main/java/kr/KWGraduate/BookPharmacy/dto/BookDto.java
- src/main/java/kr/KWGraduate/BookPharmacy/service/SearchService.java
SearchController 조회 API 호출시 List가 아닌 Page로 반환하도록 수정
SearchController 조회 API 호출시 List가 아닌 Page로 반환하도록 수정
> [Refactor] SearchController 조회 API 호출시 List가 아닌 Page로 반환하도록 수정

- src/main/java/kr/KWGraduate/BookPharmacy/controller/BoardController.java
- src/main/java/kr/KWGraduate/BookPharmacy/controller/PrescriptionController.java
- src/main/java/kr/KWGraduate/BookPharmacy/dto/board/request/BoardCreateDto.java
- src/main/java/kr/KWGraduate/BookPharmacy/dto/board/request/BoardModifyDto.java
- src/main/java/kr/KWGraduate/BookPharmacy/dto/prescription/request/PrescriptionCreateDto.java
- src/main/java/kr/KWGraduate/BookPharmacy/dto/prescription/request/PrescriptionModifyDto.java
- src/main/java/kr/KWGraduate/BookPharmacy/entity/Keyword.java
- src/main/java/kr/KWGraduate/BookPharmacy/service/BoardService.java
- src/main/java/kr/KWGraduate/BookPharmacy/service/KeywordBiMapService.java
- src/main/java/kr/KWGraduate/BookPharmacy/service/PrescriptionService.java
- src/test/java/kr/KWGraduate/BookPharmacy/service/BoardServiceTest.java
- src/test/java/kr/KWGraduate/BookPharmacy/service/PrescriptionServiceTest.java
고민 게시판 및 처방전 관련 리펙토링
closed #119
* /api/prescription 에서 bookId가 아닌 book isbn으로 조회
* /api/board에서 page파라미터 수정
* /api/board생성 후 값이 나오는지 확익
* 모든 게시글을 조회하는 url주소에 all추가
* 게시판 만들 때 키워드가 아닌 한글 키워드로 인자를 받도록 수정
* 반환값 responseEntity로 수정
* 고민 키워드에 기타 추가
> [Refactor] 고민 게시판 및 처방전 관련 리펙토링

- src/main/java/kr/KWGraduate/BookPharmacy/config/Domain.java
- src/main/java/kr/KWGraduate/BookPharmacy/controller/BoardController.java
- src/main/java/kr/KWGraduate/BookPharmacy/controller/BoardKeywordController.java
- src/main/java/kr/KWGraduate/BookPharmacy/dto/board/request/BoardCreateDto.java
- src/main/java/kr/KWGraduate/BookPharmacy/dto/board/request/BoardModifyDto.java
- src/main/java/kr/KWGraduate/BookPharmacy/service/BoardKeywordService.java
- src/main/java/kr/KWGraduate/BookPharmacy/service/BoardService.java
- src/test/java/kr/KWGraduate/BookPharmacy/service/BoardKeywordServiceTest.java
키워드를 한글 키워드가 아닌 백엔드 서버의 키워드로 변경
closed #121 
키워드를 한글 키워드가 아닌 백엔드 서버의 키워드로 변경
> [Refactor] 키워드를 한글 키워드가 아닌 백엔드 서버의 키워드로 변경

- src/main/java/kr/KWGraduate/BookPharmacy/domain/book/api/BookSearchController.java
- src/main/java/kr/KWGraduate/BookPharmacy/domain/book/dto/request/BookSearchRequestDto.java
- src/main/java/kr/KWGraduate/BookPharmacy/domain/book/dto/response/BookSearchResponseDto.java
- src/main/java/kr/KWGraduate/BookPharmacy/domain/book/repository/BookRepository.java
- src/main/java/kr/KWGraduate/BookPharmacy/domain/book/service/BookSearchService.java
- src/main/java/kr/KWGraduate/BookPharmacy/domain/keyworditem/service/KeywordItemSearchService.java
키워드와 함께 책을 검색하는 로직 추가
- 키워드와 동시에 책을 검색하는 서비스 추가
- 키워드로 책 검색하는 로직 추가
> [Feat] 키워드와 함께 책을 검색하는 로직 추가

- src/main/java/kr/KWGraduate/BookPharmacy/domain/client/api/UserController.java
- src/main/java/kr/KWGraduate/BookPharmacy/domain/client/domain/Client.java
- src/main/java/kr/KWGraduate/BookPharmacy/domain/client/dto/request/ClientJoinDto.java
- src/main/java/kr/KWGraduate/BookPharmacy/domain/client/dto/request/ClientUpdateDto.java
- src/main/java/kr/KWGraduate/BookPharmacy/domain/client/dto/response/ClientMainPageDto.java
- src/main/java/kr/KWGraduate/BookPharmacy/domain/client/dto/response/ClientMypageDto.java
- src/main/java/kr/KWGraduate/BookPharmacy/domain/client/dto/response/ClientResponseDto.java
- src/main/java/kr/KWGraduate/BookPharmacy/domain/client/service/ClientOccupationMapService.java
- src/main/java/kr/KWGraduate/BookPharmacy/domain/client/service/ClientService.java
- src/main/java/kr/KWGraduate/BookPharmacy/global/security/oauth/filter/Oauth2SuccessHandler.java
회원 관련 전반적인 리펙토링 및 api 기능 추가
#closed #131
* 아이디 중복 확인 api
* 닉네임 중목 확인 api
* 자기소개 필드 추가
* 비밀번호 길이 필드 추가
* 직업을 나타내는 키 값 매칭
* 메인페이지에 회원정보가져오는 api추가
* 회원가입 api birth값 추가
* 회원 정보 수정 api 및 추가
* oauth2 성공시 프론트로 리다이렉션하는 코드 수정
* 회원정보를 받아오는 @AuthenticationPrincipal어노테이션인자 추가
* 안쓰이는 로직 삭제
* 회원조회나 수정 시 직업정보 한글로 입출력하도록 수정
* dto이름 변경
> [Refactor] 회원 관련 전반적인 리펙토링 및 api 기능 추가

- src/main/java/kr/KWGraduate/BookPharmacy/domain/board/domain/Board.java
- src/main/java/kr/KWGraduate/BookPharmacy/domain/client/api/UserController.java
- src/main/java/kr/KWGraduate/BookPharmacy/domain/client/dto/request/ClientNicknameDto.java
- src/main/java/kr/KWGraduate/BookPharmacy/domain/client/dto/request/ClientPasswordUpdateDto.java
- src/main/java/kr/KWGraduate/BookPharmacy/domain/client/dto/response/ClientMypageDto.java
- src/main/java/kr/KWGraduate/BookPharmacy/domain/client/service/ClientService.java
마이페이지 api수정
1. mypage에 리턴되는 dto의 오타 수정
2. 닉네임을 수정하는 dto생성 및 로직 수정
3. 패스워드를 수정하는 dto생성 및 로직 수정
4. board의 status값 제거로 인한 어노테이션 값 수정
> [Refactor] 마이페이지 api수정

- src/main/java/kr/KWGraduate/BookPharmacy/domain/onelineprescription/api/OneLinePrescriptionController.java
- src/main/java/kr/KWGraduate/BookPharmacy/domain/onelineprescription/repository/OneLinePrescriptionRepository.java
- src/main/java/kr/KWGraduate/BookPharmacy/domain/onelineprescription/service/OneLinePrescriptionService.java
한줄처방 검색어 또는 키워드로 조회 기능 추가
closed #146 
- 한줄처방 검색어 또는 키워드로 조회 기능 추가 ( 레포지토리, 서비스, 컨트롤러 계층 )
> [Feat] 한줄처방 검색어 또는 키워드로 조회 기능 추가

- src/main/java/kr/KWGraduate/BookPharmacy/domain/keyword/domain/BoardKeywordQuestion.java
- src/main/java/kr/KWGraduate/BookPharmacy/domain/keyword/domain/Keyword.java
- src/main/java/kr/KWGraduate/BookPharmacy/domain/keyword/domain/QuestionDistractor.java
- src/main/java/kr/KWGraduate/BookPharmacy/domain/keyword/service/BoardKeywordService.java
질문사항 수정
closed #150
* 공통질문 2를 한달의 몇권을 읽는지 수정하기
* 상세질문을 위로 올리기
* 경제와 철학 세부질문 1개로 수정하기
> [Refactor] 질문사항 수정

- src/main/java/kr/KWGraduate/BookPharmacy/domain/category/repository/CategoryRepository.java
- src/main/java/kr/KWGraduate/BookPharmacy/domain/client/dto/request/ClientJoinDto.java
- src/main/java/kr/KWGraduate/BookPharmacy/domain/client/service/ClientService.java
- src/main/java/kr/KWGraduate/BookPharmacy/domain/interest/domain/Interest.java
- src/main/java/kr/KWGraduate/BookPharmacy/domain/interest/dto/request/InterestRequestDto.java
- src/main/java/kr/KWGraduate/BookPharmacy/domain/interest/dto/response/InterestResponseDto.java
- src/main/java/kr/KWGraduate/BookPharmacy/domain/interest/repository/InterestRepository.java
- src/main/java/kr/KWGraduate/BookPharmacy/domain/interest/service/InterestService.java
- src/test/java/kr/KWGraduate/BookPharmacy/repository/AnswerRepositoryTest.java
- src/test/java/kr/KWGraduate/BookPharmacy/repository/OneLinePrescriptionRepositoryTest.java
- src/test/java/kr/KWGraduate/BookPharmacy/repository/PrescriptionRepositoryTest.java
- src/test/java/kr/KWGraduate/BookPharmacy/service/ClientServiceTest.java
유저 관심사 테이블 및 입력 API 작성
closed #149 
- 회원가입시 유저관심사도 함께 받도록 DTO 수정
- ClientService에서 관심사목록과 유저의 연관관계 주입하도록 작성
- List<String> CategoryList로 List<Category> 조회하는 기능 추가
- 일부 Test 코드 변경사항 수정
> [Feat] 유저 관심사 테이블 및 입력 API 작성

- src/main/java/kr/KWGraduate/BookPharmacy/domain/board/repository/BoardRepository.java
- src/main/java/kr/KWGraduate/BookPharmacy/domain/board/service/BoardService.java
- src/main/java/kr/KWGraduate/BookPharmacy/domain/book/repository/BookRepository.java
책 상세정보 조회 오류 및 기타 수정
- 키워드가 없는 책 상세정보 조회 오류
- Board DTO에 대해 페이지 정보와 함께 제공하도록 수정
> [Refactor] 책 상세정보 조회 오류 및 기타 수정

- src/main/java/kr/KWGraduate/BookPharmacy/domain/board/api/BoardController.java
- src/main/java/kr/KWGraduate/BookPharmacy/domain/board/repository/BoardRepository.java
- src/main/java/kr/KWGraduate/BookPharmacy/domain/board/service/BoardService.java
- src/main/java/kr/KWGraduate/BookPharmacy/domain/book/repository/BookRepository.java
- src/main/java/kr/KWGraduate/BookPharmacy/domain/category/repository/CategoryRepository.java
- src/main/java/kr/KWGraduate/BookPharmacy/domain/client/dto/request/ClientJoinDto.java
- src/main/java/kr/KWGraduate/BookPharmacy/domain/client/service/ClientService.java
- src/main/java/kr/KWGraduate/BookPharmacy/domain/interest/domain/Interest.java
- src/main/java/kr/KWGraduate/BookPharmacy/domain/interest/dto/request/InterestRequestDto.java
- src/main/java/kr/KWGraduate/BookPharmacy/domain/interest/dto/response/InterestResponseDto.java
- src/main/java/kr/KWGraduate/BookPharmacy/domain/interest/repository/InterestRepository.java
- src/main/java/kr/KWGraduate/BookPharmacy/domain/interest/service/InterestService.java
- src/main/java/kr/KWGraduate/BookPharmacy/domain/keyword/domain/BoardKeywordQuestion.java
- src/main/java/kr/KWGraduate/BookPharmacy/domain/keyword/domain/Keyword.java
- src/main/java/kr/KWGraduate/BookPharmacy/domain/keyword/domain/QuestionDistractor.java
- src/main/java/kr/KWGraduate/BookPharmacy/domain/keyword/service/BoardKeywordService.java
- src/main/java/kr/KWGraduate/BookPharmacy/domain/onelineprescription/api/OneLinePrescriptionController.java
- src/main/java/kr/KWGraduate/BookPharmacy/domain/onelineprescription/domain/OneLinePrescription.java
- src/main/java/kr/KWGraduate/BookPharmacy/domain/onelineprescription/dto/response/OneLineResponseDto.java
- src/main/java/kr/KWGraduate/BookPharmacy/domain/onelineprescription/service/OneLinePrescriptionService.java
- src/test/java/kr/KWGraduate/BookPharmacy/repository/AnswerRepositoryTest.java
- src/test/java/kr/KWGraduate/BookPharmacy/repository/OneLinePrescriptionRepositoryTest.java
- src/test/java/kr/KWGraduate/BookPharmacy/repository/PrescriptionRepositoryTest.java
- src/test/java/kr/KWGraduate/BookPharmacy/service/ClientServiceTest.java
> [Merge] 메인 브랜치로부터 병합

- src/main/java/kr/KWGraduate/BookPharmacy/global/security/common/util/CookieType.java
> [Refactor] 쿠키값 사라지는 버그 수정

- src/main/java/kr/KWGraduate/BookPharmacy/domain/onelineprescription/api/OneLineEmotionController.java
- src/main/java/kr/KWGraduate/BookPharmacy/domain/onelineprescription/domain/OneLineHelpfulEmotion.java
- src/main/java/kr/KWGraduate/BookPharmacy/domain/onelineprescription/domain/OneLineLikeEmotion.java
- src/main/java/kr/KWGraduate/BookPharmacy/domain/onelineprescription/domain/OneLinePrescription.java
- src/main/java/kr/KWGraduate/BookPharmacy/domain/onelineprescription/repository/OneLineHelpfulEmotionRepository.java
- src/main/java/kr/KWGraduate/BookPharmacy/domain/onelineprescription/repository/OneLineLikeEmotionRepository.java
- src/main/java/kr/KWGraduate/BookPharmacy/domain/onelineprescription/service/OneLineHelpfulEmotionService.java
- src/main/java/kr/KWGraduate/BookPharmacy/domain/onelineprescription/service/OneLineLikeEmotionService.java
'좋아요, 도움이 되었어요' 기능 추가
closed #163 
- '좋아요, 도움이 되었어요' 엔티티/레포지토리/서비스/컨트롤러 계층 추가
- 한줄처방에 좋아요/도움이되었어요 개수 필드 추가
> [Feat] '좋아요, 도움이 되었어요' 기능 추가 

- src/main/java/kr/KWGraduate/BookPharmacy/domain/board/dto/response/BoardMyPageDto.java
내 게시판 가지고 오는 api에 nickname추가
closed #179
내 게시판 가지고 오는 api에 nickname추가
> [Refactor] 내 게시판 가지고 오는 api에 nickname추가

- src/main/java/kr/KWGraduate/BookPharmacy/global/infra/fastapi/FastApiService.java
- src/test/java/kr/KWGraduate/BookPharmacy/global/infra/fastapi/FastApiServiceTest.java
fastapi와 연동
closed #157 
현재 주소는 local로 되어있는데 ec2환경세팅되는대로 바꾸겠습니다!
> [Feat] fastapi와 연동

- src/main/java/kr/KWGraduate/BookPharmacy/BookPharmacyApplication.java
- src/main/java/kr/KWGraduate/BookPharmacy/domain/book/api/BestSellerBookController.java
- src/main/java/kr/KWGraduate/BookPharmacy/domain/book/api/NewBookController.java
- src/main/java/kr/KWGraduate/BookPharmacy/domain/book/domain/BestSellerBook.java
- src/main/java/kr/KWGraduate/BookPharmacy/domain/book/domain/NewBook.java
- src/main/java/kr/KWGraduate/BookPharmacy/domain/book/dto/response/BestSellerBookDto.java
- src/main/java/kr/KWGraduate/BookPharmacy/domain/book/dto/response/NewBookDto.java
- src/main/java/kr/KWGraduate/BookPharmacy/domain/book/dto/response/ReadExperienceTop10Dto.java
- src/main/java/kr/KWGraduate/BookPharmacy/domain/book/repository/BestSellerBookRepository.java
- src/main/java/kr/KWGraduate/BookPharmacy/domain/book/repository/NewBookRepository.java
- src/main/java/kr/KWGraduate/BookPharmacy/domain/book/service/BestSellerBookService.java
- src/main/java/kr/KWGraduate/BookPharmacy/domain/book/service/NewBookService.java
- src/main/java/kr/KWGraduate/BookPharmacy/domain/readexperience/repository/ReadExperienceRepository.java
- src/main/java/kr/KWGraduate/BookPharmacy/global/common/service/BookSchedulerService.java
- src/test/java/kr/KWGraduate/BookPharmacy/repository/OneLinePrescriptionRepositoryTest.java
- src/test/java/kr/KWGraduate/BookPharmacy/service/BestSellerBookServiceTest.java
- src/test/java/kr/KWGraduate/BookPharmacy/service/OneLinePrescriptionServiceTest.java
인기/신간도서 관련 기능 및 API 작성
closed #176 
- 인기/신간도서 관련 기능 및 API 작성
- 인기도서 스프링 스케쥴러 적용
> [Feat] 인기/신간도서 관련 기능 및 API 작성

- src/main/java/kr/KWGraduate/BookPharmacy/domain/board/event/BoardUpdatedEvent.java
- src/main/java/kr/KWGraduate/BookPharmacy/domain/board/service/BoardService.java
- src/main/java/kr/KWGraduate/BookPharmacy/domain/readexperience/event/ReadExperienceUpdatedEvent.java
- src/main/java/kr/KWGraduate/BookPharmacy/domain/readexperience/service/ReadExperienceService.java
- src/main/java/kr/KWGraduate/BookPharmacy/global/infra/fastapi/FastApiRequestListener.java
- src/main/java/kr/KWGraduate/BookPharmacy/global/infra/fastapi/FastApiService.java
파이썬 서버로 요청보내는 로직 추가
closed #181 
* 이벤트 핸들러 추가
* 파이썬 서버 url수정
* 추천에 관한 이벤트 추가
* 서비스 코드에 로직 추가
> [Feat] 파이썬 서버로 요청보내는 로직 추가

- src/main/java/kr/KWGraduate/BookPharmacy/domain/book/repository/BookRepository.java
- src/test/java/kr/KWGraduate/BookPharmacy/repository/BookRepositoryTest.java
> [Refactor] 책 키워드 검색 오류 일부 수정

- src/main/java/kr/KWGraduate/BookPharmacy/domain/board/dto/response/BoardConcernPageDto.java
모든 게시판을 조회하는 api에 description을 추가
모든 게시판을 조회하는 api에 description을 추가
> [Refactor] 모든 게시판을 조회하는 api에 description을 추가

- src/main/java/kr/KWGraduate/BookPharmacy/domain/onelineprescription/dto/response/OneLineResponseDto.java
- src/main/java/kr/KWGraduate/BookPharmacy/domain/onelineprescription/repository/OneLineLikeEmotionRepository.java
- src/main/java/kr/KWGraduate/BookPharmacy/domain/onelineprescription/service/OneLineHelpfulEmotionService.java
- src/main/java/kr/KWGraduate/BookPharmacy/domain/onelineprescription/service/OneLineLikeEmotionService.java
- src/main/java/kr/KWGraduate/BookPharmacy/domain/onelineprescription/service/OneLinePrescriptionService.java
[Refactor] Emotion 추가 및 삭제 서비스 로직 오류 수정
closed #194 
- 조인이 아닌 한줄처방의 조회수 컬럼을 참조하도록 코드 변경
- 한줄처방 좋아요/도움이되었어요가 이미 존재할 경우 추가되지 않도록 코드 변경
> [Refactor] Emotion 추가 및 삭제 서비스 로직 오류 수정

- src/main/java/kr/KWGraduate/BookPharmacy/domain/board/api/BoardController.java
- src/main/java/kr/KWGraduate/BookPharmacy/domain/board/service/BoardService.java
- src/main/java/kr/KWGraduate/BookPharmacy/domain/book/api/BookSearchController.java
- src/main/java/kr/KWGraduate/BookPharmacy/domain/book/domain/Book.java
- src/main/java/kr/KWGraduate/BookPharmacy/domain/book/dto/response/BookDto.java
- src/main/java/kr/KWGraduate/BookPharmacy/domain/book/repository/BookRepository.java
- src/main/java/kr/KWGraduate/BookPharmacy/domain/book/service/BookSearchService.java
- src/main/java/kr/KWGraduate/BookPharmacy/domain/book/service/BookService.java
- src/main/java/kr/KWGraduate/BookPharmacy/domain/client/domain/Client.java
- src/main/java/kr/KWGraduate/BookPharmacy/domain/onelineprescription/service/OneLinePrescriptionService.java
책 조회시 처방전 개수 및 인기순으로 조회기능 추가
- 처방전 개수, 인기순으로 책 조회할 수 있도록 수정
- 한줄처방 및 고민 작성시 Count 개수 관리되도록 수정
> [Refactor] 책 조회시 처방전 개수 및 인기순으로 조회기능 추가

- src/main/java/kr/KWGraduate/BookPharmacy/domain/book/api/BookSearchController.java
- src/main/java/kr/KWGraduate/BookPharmacy/domain/book/domain/InterestRecommend.java
- src/main/java/kr/KWGraduate/BookPharmacy/domain/book/dto/response/ClientBasedRecommendDto.java
- src/main/java/kr/KWGraduate/BookPharmacy/domain/book/repository/InterestRecommendRepository.java
- src/main/java/kr/KWGraduate/BookPharmacy/domain/book/service/RecommendService.java
- src/main/java/kr/KWGraduate/BookPharmacy/domain/category/repository/CategoryRepository.java
- src/main/java/kr/KWGraduate/BookPharmacy/domain/category/service/CategoryService.java
- src/main/java/kr/KWGraduate/BookPharmacy/domain/readexperience/service/ReadExperienceService.java
- src/test/java/kr/KWGraduate/BookPharmacy/service/ReadExperienceServiceTest.java
[Feat] 관심사 기반 추천 기능 추가
- 관심사 기반 추천 기능 추가
- 카테고리 페이지에서 대분류 id 순서로 응답하도록 수정
> [Feat] 관심사 기반 추천 기능 추가

- src/main/java/kr/KWGraduate/BookPharmacy/domain/client/dto/response/ClientMypageDto.java
마이 페이지에서 출력할때 oauth로그인 여부 출력
마이 페이지에서 출력할때 oauth로그인 여부 출력
> [Refactor] 마이 페이지에서 출력할때 oauth로그인 여부 출력

- src/main/java/kr/KWGraduate/BookPharmacy/domain/book/repository/ClientRecommendRepository.java
> [Refactor] 사용자 책 추천 시 쿼리 문 수정

- src/main/java/kr/KWGraduate/BookPharmacy/domain/prescription/dto/response/PrescriptionBoardPageDto.java
> [Refactor] dto에 isbn추가
